### PR TITLE
Add basic visitor support

### PR DESCRIPTION
**Pull request by etcinitd**
**Not ready to merge yet!**
Hi @antonmedv 
I needed a feature that allows me to walk the parsed AST (without evaluation) to find variables and functions used in an expression. This was my first try that I wanted to get your opinions on. 
What do you think? Is it the right approach? How can I make it good enough to be merged into the upstream master?
Cheers,
Amir

### CODE REVIEW

**Comment by antonmedv** [comment]
I was thinking about adding visitor myself. But still haven't found time for this. Will be cool to see API there custom visitor can define only needed nodes wishing to visit. 

See babel for example, pretty cool  implementation.

**Comment by etcinitd** [comment]
Then we need some form of defining node types, I guess. For example, we can make node structs exported. Any other ideas?

**Comment by antonmedv** [comment]
If visitor will be added, AST nodes must be exported.

**Comment by antonmedv** [comment]
Will be solved in #21

**Pull request closed without merging**
