### PR TITLE
Match string in string

### PR DESCRIPTION
**Pull request by relvacode**
Adds ability to match if `"foo" in "foobar"`

### CODE REVIEW

**Comment by antonmedv** [comment]
But we have _matches_.  It does same think:

```ruby
"foo" matches "foobar"
```

Is it?

**Comment by relvacode** [comment]
These examples don't work in the same way as they would with `in` as they do with a regular expression match. To me they seem different enough.

```
"foobar" matches "foo"  (should be false)
"foo" matches "foobar"  (should be true)
"foobar" matches ""     (should be false)
"$1" matches "$1.50"    (should be true)
"foo" matches "foo.bar" (should be true)
```

**Comment by antonmedv** [comment]
I see, not `in` operator supports both maps and arrays. Do you think it will be okay to override strings too?

**Comment by relvacode** [comment]
I don't see why not. It works for me, would you like me to add tests for that?

**Comment by antonmedv** [comment]
Ok, just please add type checks for strict mode. (See type.go)

**Comment by relvacode** [comment]
Type checks added

**Comment by antonmedv** [comment]
After discussion with my team we decided not to add this functionality as it can be error prone.
For example `"" in bar` if user expects bar to be an array he may check for empty string properly, but if bar ended up being string this check will always be try. 
(In fact we see this errors in python)

As alternative is to define helper method:

```ruby
Contains("foobar", "bar")
``` 

What do you think?

**Comment by antonmedv** [comment]
I'm working on next expr version and it will have `contains` operator.

**Comment by antonmedv** [comment]
Will be solved in #21

**Pull request closed without merging**
