### PR TITLE
Updated the test with operator overloading

### PR DESCRIPTION
**Pull request by wintermute-cds**

### CODE REVIEW

**Comment by wintermute-cds** [comment]
It is hard to explain. It is an edge case that happens to be important to us.

**Comment by antonmedv** [comment]
I’ll release new release tomorrow.

**Comment by wintermute-cds** [comment]
It is realy hard to explain. Strange thing in Go. Thank you for looking at it.

**Comment by antonmedv** [comment]
Released v1.4.5 with a fix. 

Also, consider adding your project to [Who is using Expr](https://github.com/antonmedv/expr#who-is-using-expr) section.

**Pull request closed without merging**
