### PR TITLE
support temporary override variables of env.

### PR DESCRIPTION
**Pull request by zhuah**
this pr provide a way for user to override/attach new variables to env instance.

### CODE REVIEW

**Comment by antonmedv** [comment]
So what is use case? Why not just use map or extend struct?

**Comment by zhuah** [comment]
I'm creating a template engine, which should support `if`,`else`,`elif`,`for`, while in a `for` block, user will introduce some new local variable such as `idx`,`val` or `key`,`val`.

i found no way to wrap current env with some temporary variables, what i can do is copy all variables/functions from old env to a new map and adds the new variables, and it's not easy to have same behavior with the `vm` package.

**Comment by antonmedv** [comment]
Why not just override local vars in env? Set old value back after loop scope. Keep a stack of loops with var overrides.

**Comment by zhuah** [comment]
the old env may be a structure, and local variable name is defined by user.

**Pull request closed without merging**
