### PR TITLE
WIP: try marshall

### PR DESCRIPTION
**Pull request by rucciva**
#52

### CODE REVIEW

**Comment by rucciva** [comment]
@antonmedv , any feedback?

**Comment by antonmedv** [comment]
This is awesome! So now program goes gob to base64 to json?

**Comment by antonmedv** [comment]
What with performance?

**Comment by rucciva** [comment]
> So now program goes gob to base64 to json

Yup, since expr use a lot of Interface{}, we need to encode type information so that it can be decoded-back correctly, and binary encoder like gob do just that . But since we need string for json, base64 is needed.

>What with performance?

Haven't tested it yet, but the step is similliar with the one i write when i first commented on the issue, just now we used gob instead of go-codec.

**Comment by rucciva** [comment]
What about the *regexp.Regexp wrapping? Is that acceptable?

**Comment by antonmedv** [comment]
I think it’s okay, since we anyway need to compile regex on unmarshal before runtime.

**Comment by rucciva** [comment]
Cool then.

**Comment by antonmedv** [comment]
Can you also add benchmarks to the repo so we can track unmarshal performance over time.

**Comment by rucciva** [comment]
Sure...

**Comment by rucciva** [comment]
hi @antonmedv , based on the benchmark test, gob is not a fast encoded. it doesn't increase significance performance.

I've tried with go-codec's binc, but i'm still stuck at decoding *Regexp back since vm.Program only contains nil interface `Constant`

**Comment by rucciva** [comment]
Btw, if parameters passed when compiling has methods, it needs to be registered to gob for successful marshal.

**Comment by antonmedv** [comment]
This is sad. Let’s think, maybe we can throw away something unnecessary for increasing performance?

**Comment by rucciva** [comment]
I am afraid there is none.

I think we need a better encoding-decoding mechanism in terms of speed. But i am afraid it is harder with said mechanism to unmarshall the type back correctly due to the usage if interface{}

**Comment by antonmedv** [comment]
Another possibility is to split constants into separate list for `[]vm.Call`, `[]regex`, `[]string`, etc. 
But this requires a lot of internal changes. 
Maybe we need to take another way, and safe original source on marshal and recompile it on unmarshal. What do you think @rucciva?

**Comment by rucciva** [comment]
> Maybe we need to take another way, and safe original source on marshal and recompile it on unmarshal.

hmm,, i don't think combining unmarshal and recompile is a good idea, because the point of marshall-unmarshal is to avoid recompile. Or do you mean a different kind of recompile?

btw, i've opened up an [issue](https://github.com/ugorji/go/issues/322) regarding decoding back pointer to interface{}. i've tried with go-binc  and it is 5x faster than recompile (still failed to decode-back pointer of Regexp). But the caveat is that any custom parameters type need to provide [extension](https://godoc.org/github.com/ugorji/go/codec#BytesExt) and expr need to expose function to register said extension to go-binc handler

**Comment by antonmedv** [comment]
I tested _json_ vs  _gob-base64-json`:
```
Benchmark_brg/unmarshall_v1-8         	   20906	     53843 ns/op
Benchmark_brg/unmarshall_v2-8         	   26377	     43177 ns/op
```

I think if we want marshal/unmarshal functionality to work correctly to find a better way of doing it.

**Comment by rucciva** [comment]
hi @antonmedv , sorry didn't catch the notification

>I think if we want marshal/unmarshal functionality to work correctly to find a better way of doing it.

yup, in terms of performance, i think its the binary marshaller that we need to find.  Try replacing gob with go-codec (ignoring regexp and other custom type) and you will get around 4x performance improvement. But the downside is adding custom type will be harder, including custom parameters.  

but in terms of functionality correctness (correctly marshall and then unmarshall), using gob maybe the best way, since it is easier for custom type

**Pull request closed without merging**
